### ISSUE TITLE
binary download error. (with slapt-get)

### ISSUE THREAD

**Issue by zw963** [mateslackbuilds/msb#10] opened 2015-09-03 11:46 UTC
1. add source to `slapt-getrc`, with this: ``SOURCE=http://slackware.org.uk/msb/14.1/1.10/x86_64/``

2. slapt-get --update, update cache.

3. slapt-get install mate-desktop

get following message:
```sh
Reading Package Lists...Done
The following NEW packages will be installed:
  mate-desktop 
0 upgraded, 0 reinstalled, 1 newly installed, 0 to remove, 0 not upgraded.
Need to get 7.4MB of archives.
After unpacking 25.7MB of additional disk space will be used.
1/1 Get http://slackware.org.uk/msb/ mate-desktop 1.10.2-x86_64-1_msb [7.4MB]...Failed to download: HTTP response code said error
```
seem like a redundant space is add to ``msb/`` in http url.

**Comment by willysr** [comment] 2015-09-03 12:01
I never use slapt-get
Try using slackpkg+

**Comment by willysr** [comment] 2015-09-03 12:02
Can you paste the repo configuration for your slapt-get?

**Comment by zw963** [comment] 2015-09-03 13:30
```sh
# Base url to directory with a PACKAGES.TXT.
# This can point to any release, ie: 9.0, 10.0, current, etc.
SOURCE=http://mirrors.163.com/slackware/slackware64-current/:OFFICIAL
#SOURCE=http://mirrors.tuna.tsinghua.edu.cn/slackware/slackware64-current/:OFFICIAL
#SOURCE=http://slackware.org.uk/slacky/slackware64-14.1
# SOURCE=http://mirror.bjtu.edu.cn/salix/x86_64/14.1/
#SOURCE=http://slackware.org.uk/salix/x86_64/14.1/
#SOURCE=http://www.slackware.com/~alien/multilib/14.1/
#SOURCE=http://www.slackware.com/~alien/slackbuilds/
#SOURCE=https://slackonly.com/pub/packages/14.1-x86_64/
SOURCE=http://slackware.org.uk/msb/14.1/1.10/x86_64/
```

**Comment by willysr** [comment] 2015-09-03 14:43
I have no idea. The configuration seems normal from here
Anyway, i will close this as this is not relevant to MSB. 
I would suggest to use slackpkg+ for your convenience

**Closed by willysr** 2015-09-03 14:43 UTC

**Comment by zw963** [comment] 2015-09-04 06:47
hi, I install msb binary version, it can not login, because it not worked with slackware current)

so, I recompile it with github repo, it seem like install successfully, but my Terminal is broken.

before it look like this:  
https://camo.githubusercontent.com/64de53f497cb0676ce50b98f319ac633dfc06778/687474703a2f2f7a773936332e6769746875622e696f2f736e617073686f7431312e706e67

But, it now is ugly, like this:
http://zw963.github.io/snapshot18.png

**Comment by zw963** [comment] 2015-09-04 06:49
before install msb, it looks like good.

I think when I compile, it remove some useful file? or need rebuild some cache?

**Comment by willysr** [comment] 2015-09-04 07:07
binary is provided for stable releases, not for current. You need to build it from source if you are running on -current. On the other hand, there is nothing i can do about some abnormal behaviour in the display/themes since current is a moving target (it changes everytime during development cycle).

But try to use the correct mate-themes for current. It uses GTK-3-3.16 instead of GTK-3-3.8. You can override them using environment variable before running the mate-themes.SlackBuild.

We don't use any cache. You just need to build, install/upgrade and that's it. At most you just need to log out of X and run startx to get the new version.

**Comment by zw963** [comment] 2015-09-04 07:28
Thanks. though I am pool about understood this.

when i try to use xfce-terminal, it broken too.  so, it relation with the mate-themes ?

I have uninstall all mate packages, it still display broken in any terminal.

any tips what can I do? I install slackware with full install, could you give some tips
about reinstall some offical package to restore the default? 

I update this spend so long time, I hope can fix, and not need reinstall , Thanks.

**Comment by willysr** [comment] 2015-09-04 07:33
No, that's not relevant with MATE. MATE doesn't touch any other DE's configuration. It's most likely due to changes in -current. 

Are you planning to go back to stable or stay in current?
If you already move to current, i would suggest to keep using current. If you want to go back to stable, it would be better to reinstall from scratch so that you can have a clean installation.

if you are on stable, use slackpkg clean-system to remove all third party packages (including from MSB) and you can start building your own packages or use the binary version.

**Comment by zw963** [comment] 2015-09-04 11:55
Sorry, i just reinstall slackware 14.1, and then update to current, my Terminal is broken again,
this time I am not install msb anyway.

so, it really caused by slackpkg. what I do is just:
```sh
slackpkg update
slackpkg upgrade slackpkg
slackpkg new-config
slackpkg upgrade glibc-solibs
slackpkg install-new
slackpkg upgrade-all
slackpkg clean-system
```
I don't know what step cause this.

**Comment by willysr** [comment] 2015-09-04 12:00
so i think it's caused by one of the changes in current.
you need to wait until Pat fixed them or you can report it to him

anyway, to upgrade in -current you only need these steps:
slackpkg update
slackpkg install-new
slackpkg upgrade-all
slackpkg clean-system

**Comment by zw963** [comment] 2015-09-04 18:09
Thanks very much for you help, I wrote a email to info@slackware.com, I hope can fix this when
slackware 14.2 release.

**Comment by willysr** [comment] 2015-12-17 02:33
ok, i have removed the PACKAGE MIRROR
should be fixed now

**Comment by zw963** [comment] 2015-12-20 06:13
Cool. Thanks.
