### ISSUE TITLE
mate-applets master branch fails to compile on -current (5/4/2017)

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#18] opened 2017-05-05 05:40 UTC
Here is the relevant output.

 GtkWidget     *gtk_ui_manager_get_widget          (GtkUIManager          *manager,
                ^~~~~~~~~~~~~~~~~~~~~~~~~
gcc -DHAVE_CONFIG_H -I. -I../..  -DCPUFREQ_MENU_UI_DIR=\""/usr/share/mate/ui"\" -pthread -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -fPIC -MT cpufreq-monitor-factory.o -MD -MP -MF .deps/cpufreq-monitor-factory.Tpo -c -o cpufreq-monitor-factory.o cpufreq-monitor-factory.c
mv -f .deps/cpufreq-monitor.Tpo .deps/cpufreq-monitor.Po
gcc -DHAVE_CONFIG_H -I. -I../..  -DCPUFREQ_MENU_UI_DIR=\""/usr/share/mate/ui"\" -pthread -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -fPIC -MT cpufreq-monitor-procfs.o -MD -MP -MF .deps/cpufreq-monitor-procfs.Tpo -c -o cpufreq-monitor-procfs.o cpufreq-monitor-procfs.c
mv -f .deps/cpufreq-prefs.Tpo .deps/cpufreq-prefs.Po
gcc -DHAVE_CONFIG_H -I. -I../..  -DCPUFREQ_MENU_UI_DIR=\""/usr/share/mate/ui"\" -pthread -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -fPIC -MT cpufreq-monitor-sysfs.o -MD -MP -MF .deps/cpufreq-monitor-sysfs.Tpo -c -o cpufreq-monitor-sysfs.o cpufreq-monitor-sysfs.c
mv -f .deps/cpufreq-popup.Tpo .deps/cpufreq-popup.Po
mv -f .deps/cpufreq-monitor-factory.Tpo .deps/cpufreq-monitor-factory.Po
gcc -DHAVE_CONFIG_H -I. -I../..  -DCPUFREQ_MENU_UI_DIR=\""/usr/share/mate/ui"\" -pthread -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -fPIC -MT cpufreq-monitor-libcpufreq.o -MD -MP -MF .deps/cpufreq-monitor-libcpufreq.Tpo -c -o cpufreq-monitor-libcpufreq.o cpufreq-monitor-libcpufreq.c
gcc -DHAVE_CONFIG_H -I. -I../..  -DCPUFREQ_MENU_UI_DIR=\""/usr/share/mate/ui"\" -pthread -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -fPIC -MT cpufreq-monitor-cpuinfo.o -MD -MP -MF .deps/cpufreq-monitor-cpuinfo.Tpo -c -o cpufreq-monitor-cpuinfo.o cpufreq-monitor-cpuinfo.c
mv -f .deps/cpufreq-applet.Tpo .deps/cpufreq-applet.Po
cpufreq-monitor-libcpufreq.c: In function ‘cpufreq_monitor_libcpufreq_run’:
cpufreq-monitor-libcpufreq.c:117:7: warning: implicit declaration of function ‘cpupower_is_cpu_online’ [-Wimplicit-function-declaration]
   if (cpupower_is_cpu_online (cpu)) {
       ^~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/cpufreq-monitor-procfs.Tpo .deps/cpufreq-monitor-procfs.Po
mv -f .deps/cpufreq-monitor-sysfs.Tpo .deps/cpufreq-monitor-sysfs.Po
mv -f .deps/cpufreq-monitor-libcpufreq.Tpo .deps/cpufreq-monitor-libcpufreq.Po
mv -f .deps/cpufreq-monitor-cpuinfo.Tpo .deps/cpufreq-monitor-cpuinfo.Po
/bin/sh ../../libtool  --tag=CC   --mode=link gcc  -O2 -fPIC   -o mate-cpufreq-applet cpufreq-applet.o cpufreq-utils.o cpufreq-prefs.o cpufreq-selector.o cpufreq-popup.o cpufreq-monitor.o cpufreq-monitor-factory.o cpufreq-monitor-procfs.o cpufreq-monitor-sysfs.o cpufreq-monitor-libcpufreq.o cpufreq-monitor-cpuinfo.o -lmate-panel-applet-4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lcpufreq -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0 
libtool: link: gcc -O2 -fPIC -o mate-cpufreq-applet cpufreq-applet.o cpufreq-utils.o cpufreq-prefs.o cpufreq-selector.o cpufreq-popup.o cpufreq-monitor.o cpufreq-monitor-factory.o cpufreq-monitor-procfs.o cpufreq-monitor-sysfs.o cpufreq-monitor-libcpufreq.o cpufreq-monitor-cpuinfo.o  /usr/lib64/libmate-panel-applet-4.so -L/usr/lib64 /usr/lib64/libgtk-3.so /usr/lib64/libgdk-3.so /usr/lib64/libpangocairo-1.0.so /usr/lib64/libpangoft2-1.0.so /usr/lib64/libpango-1.0.so /usr/lib64/libgthread-2.0.so /usr/lib64/libatk-1.0.so /usr/lib64/libcairo-gobject.so /usr/lib64/libcairo.so /usr/lib64/libpixman-1.so /usr/lib64/libfontconfig.so /usr/lib64/libharfbuzz.so /usr/lib64/libfreetype.so -lbz2 /usr/lib64/libEGL.so /usr/lib64/libxcb-xfixes.so /usr/lib64/libgbm.so /usr/lib64/libxcb-shm.so /usr/lib64/libxcb-render.so /usr/lib64/libXrender.so /usr/lib64/libGL.so /usr/lib64/libexpat.so /usr/lib64/libxcb-dri3.so /usr/lib64/libxcb-present.so /usr/lib64/libxcb-sync.so /usr/lib64/libxshmfence.so /usr/lib64/libglapi.so /usr/lib64/libXdamage.so /usr/lib64/libXfixes.so /usr/lib64/libX11-xcb.so /usr/lib64/libxcb-glx.so /usr/lib64/libxcb-dri2.so /usr/lib64/libXxf86vm.so /usr/lib64/libXext.so /usr/lib64/libX11.so /usr/lib64/libxcb.so /usr/lib64/libXau.so /usr/lib64/libXdmcp.so /usr/lib64/libdrm.so /usr/lib64/libgdk_pixbuf-2.0.so /usr/lib64/libpng16.so -lm -lcpufreq /usr/lib64/libdbus-glib-1.so /usr/lib64/libgio-2.0.so /usr/lib64/libmount.so /usr/lib64/libblkid.so /usr/lib64/libuuid.so -lrt /usr/lib64/libgmodule-2.0.so -ldl -lz -lresolv /usr/lib64/libdbus-1.so /usr/lib64/libgobject-2.0.so /usr/lib64/../lib64/libffi.so /usr/lib64/libglib-2.0.so /usr/lib64/libpcre.so -lpthread -pthread -Wl,-rpath -Wl,/usr/lib64/../lib64 -Wl,-rpath -Wl,/usr/lib64/../lib64
cpufreq-monitor-libcpufreq.o: In function `cpufreq_monitor_libcpufreq_run':
cpufreq-monitor-libcpufreq.c:(.text+0x2df): undefined reference to `cpupower_is_cpu_online'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:579: mate-cpufreq-applet] Error 1
make[4]: Leaving directory '/tmp/msb/mate-applets-1.18.1/cpufreq/src'
make[3]: *** [Makefile:633: all-recursive] Error 1
make[3]: Leaving directory '/tmp/msb/mate-applets-1.18.1/cpufreq/src'
make[2]: *** [Makefile:606: all-recursive] Error 1
make[2]: Leaving directory '/tmp/msb/mate-applets-1.18.1/cpufreq'
make[1]: *** [Makefile:567: all-recursive] Error 1
make[1]: Leaving directory '/tmp/msb/mate-applets-1.18.1'
make: *** [Makefile:499: all] Error 2
root@Slackware64:/tmp/msb-master#

**Comment by willysr** [comment] 2017-05-05 05:46
I think it's caused by new kernel which changed it's API.

I haven't tested with new kernel yet, so it will take some time to fix this.

Thanks for reporting.

**Comment by mdinslage** [comment] 2017-05-05 05:47
Quick update, I was able to compile after applying this patch...
https://github.com/mate-desktop/mate-applets/pull/217/commits/65b6297b572b3fc8969b53ca975fc530876ba5e0

**Comment by willysr** [comment] 2017-05-05 07:50
Fixed in e2a382a374b3275b64c0926ed66b4dd3db042951

closed #18

**Closed by willysr** 2017-05-05 07:50 UTC
